#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Marallyn\Command;
use Symfony\Component\Console\Application;

$application = new Application('tools', '1.0.0');

$application->add(new Command\UnicodeCommand());
$application->add(new Command\UuidCommand());
$application->add(new Command\AuthTokenCommand());

$application->run();
