#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Marallyn\Command;
use Symfony\Component\Console\Application;

$application = new Application('unicode', '1.0.0');
$command = new Command\UnicodeCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
